name: Simulate Commits

on:
  workflow_dispatch:

jobs:
  simulate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Simulate commits
        run: |
          git config user.name "UserAAR"
          git config user.email "amil.abdullazada@gmail.com"

          # Commit 5 days ago
          echo "Simulated content from 5 days ago" > file1.txt
          git add file1.txt
          GIT_AUTHOR_DATE="2025-01-14T12:00:00" GIT_COMMITTER_DATE="2025-01-14T12:00:00" git commit -m "Commit from 5 days ago"

          # Commit today
          echo "Simulated content from today" > file2.txt
          git add file2.txt
          GIT_AUTHOR_DATE="2025-01-19T15:00:00" GIT_COMMITTER_DATE="2025-01-19T15:00:00" git commit -m "Today's commit"

          git push origin main
